apiVersion: v1
kind: Pod
metadata:
  name: microservice
  namespace: mtls-test
  labels:
    app: microservice
spec:
  imagePullSecrets:
  - name: pull-secret
  containers:
    - name: microservice
      image: docker.io/barsik/microservice:latest
      volumeMounts:
      - name: cert
        mountPath: "/cert"
        readOnly: true
      - name: cert-ca
        mountPath: "/cert-ca"
        readOnly: true
  volumes:
  - name: cert-ca
    configMap:
      name: service-ca
      defaultMode: 292
  - name: cert
    secret:
      secretName: microservice-cert
      defaultMode: 292
---
apiVersion: v1
kind: Pod
metadata:
  name: microservice-client
  namespace: mtls-test
spec:
  imagePullSecrets:
  - name: pull-secret
  containers:
  - name: microservice-client
    image: python:3.8
    args:
    - sleep
    - "1000000"
    volumeMounts:
      - name: cert
        mountPath: "/cert"
        readOnly: true
      - name: cert-ca
        mountPath: "/cert-ca"
        readOnly: true
  volumes:
  - name: cert
    secret:
      secretName: microservice-client-cert
      defaultMode: 292
  - name: cert-ca
    configMap:
      name: service-ca
      defaultMode: 292
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: microservice-cert
  name: microservice
  namespace: mtls-test
spec:
  type: NodePort
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: service-ca
  namespace: mtls-test

